### ISSUE TITLE
project numbers not sorted numerically

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#24]
project number `pn` is treated as string, therefore "25" comes after "249"

**Comment by fschoell** [comment]
Meeting Discussion: Only numeric project numbers

**Comment by sebastian-leidig** [comment]
when deploying, `Child` records need to be converted once:

    childManager.getAll().then(function (data) {
        data.forEach(function (child) {
            child.pn = parseInt(child.pn);
            child.update();
        });
    });
