### ISSUE TITLE
Logout doesn't really log you out

### ISSUE THREAD

**Issue by sanindya-iiitd** [NGO-DB/helgo_db#31]
Before logging in, the left pane shows nothing.
After logging in, the left pane shows options - Overview, Children, Schools.
After logging out, these options should no longer be visible nor should they be accessible.
As of now, these options are visible even after logging out and clicking on the same will take you to the corresponding pages without asking you to login.

**Comment by sebastian-leidig** [comment]
I think this is fixed now. Thanks!
