### ISSUE TITLE
Issues with the new project structure

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/helgo_db#39]
As we might have different npm versions or different global npm packages installed we all should test the grunt tasks `serve`, `test` and `build`. If you encounter any problems you can post the bugs here. 

For me there were a lot npm packages missing (the new version of npm unfortunately doesn't install peer dependencies by default, so I need to add them manually). Furthermore I have [this](https://github.com/gruntjs/grunt-contrib-imagemin/issues/321) problem when I try to execute `grunt build`. Somehow the installation of `optipng-bin` failed, but this could be a temporary error as I received a `503` error.

**Comment by fschoell** [comment]
`grunt serve` and `grunt build` are working for me now. `grunt test` starts the karma testing framework in chrome but then somehow crashes (chances are good that this is an issue of our app rather than the testing environment though).

**Comment by sebastian-leidig** [comment]
Thanks, `grunt serve` and `grunt build` also work for me now after pulling your changes and running `npm install` and `bower install` again.

Let's look at the `test` problem when we start adding actual test code ...

**Comment by sebastian-leidig** [comment]
new structure is now on the `master` branch

**Comment by sebastian-leidig** [comment]
As nobody is complaining, I guess these issues are solved.
