### ISSUE TITLE
Undo/Reset changes

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#41]
In addition to the `Save` button there should be an option to undo/reset changes made to a record (Child/School/etc.).

**Comment by fschoell** [comment]
I don't think we should name the button "Reset" as it indicates that all data will be reset and not only the changes. I would either name the button "Undo" and only reset the changes the user currently made (without leaving the current child page) or name the button "Cancel" and forward the user to the child/school/... overview page.
