### ISSUE TITLE
cryptographic hash function for user passwords

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/helgo_db#42]
We should use a cryptographic hash function for the user passwords as the FNV-1a hash is pretty easy to bruteforce due to its speed. 

Is there currently a productive database in use or does one exist? If not I would change this in the 1.0.1 milestone to prevent database issues in the future (and it's a pretty small change too).

**Comment by sebastian-leidig** [comment]
Good point, let's do this soon.

There is a "productive" database with two users (socialworkers) and the demo database with its `demo` user. Adapting their passwords can be done manually.

**Comment by sebastian-leidig** [comment]
@fschoell Do you have a suitable crypto in mind?
Or should somebody do some research?

**Comment by fschoell** [comment]
I would use PBKDF2. It allows some configuration like the number of iterations and the key size. And it supports salts.

**Comment by sebastian-leidig** [comment]
Isn't the salt useless if everybody can see it in the (local) Javascript code? -> c248b0f99fd4156642e40d88a9a56474ce41c766

**Comment by fschoell** [comment]
The salt is mostly used to prevent an attacker from comparing the password hashes with a pre-calculated hash table ("rainbow table attacks"). So it's not really a problem that the salt value is publicly available and we can easily change it for the productive systems (which then will use uglified javascript, so the application has to be "reverse engineered" to recover the salt).

**Comment by sebastian-leidig** [comment]
We currently have one "central" salt for all users. CouchDB internally also uses `pbkdf2` but saves salt and iteration directly with each user password (is that best practice?):

    {"name":"demo"
    "password_scheme":"pbkdf2","iterations":10,
    "derived_key":"cc5dc545da269b3c433bcaa5f1643a570b8cfcf3",
    "salt":"57d194e292af5c57e15cf063951f1658",

Maybe we should also use a random salt for each user and save it in the db record?

**Comment by sebastian-leidig** [comment]
Note: To save the password generated by `CryptoJS.PBKDF2()` convert it to `string` - otherwise it is a complex javascript object.

    "" + CryptoJS.PBKDF2( ... )

**Comment by sebastian-leidig** [comment]
@fschoell Should we replace the vendor library in the repo with a `bower` dependency?
-> https://www.npmjs.com/package/crypto-js

**Comment by fschoell** [comment]
Tried it but it's not working out-of-the box (complaining about CryptoJS not defined). Not sure how to include it in AngularJS the right way. It seems they are using RequireJS, but that would be some sort of an overkill to include just for this library.

**Comment by sebastian-leidig** [comment]
Okay, then let's leave it like that for now
