### ISSUE TITLE
Document our Git Branch System

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#45]
add information about `master` and `feature` branches and the commit/merge/... workflow here: https://github.com/NGO-DB/helgo_db/wiki/Contribute

**Comment by sebastian-leidig** [comment]
@fschoell Could you add the information from our last meeting?

**Comment by fschoell** [comment]
Yes I will add them, been really busy the last couple of days.

**Comment by fschoell** [comment]
I added some guidelines for the contribution. Feedback is welcome. 

The point about testing the pull requests is open for discussion, as we don't have any unit tests yet and jshint isn't used as well. I think this would be a good point to discuss in our next meeting.

**Comment by sebastian-leidig** [comment]
adapted the wiki page according to our discussions
