### ISSUE TITLE
Save files and images separate from main database

### ISSUE THREAD

**Issue by sebastian-leidig** [NGO-DB/helgo_db#61]
It is probably smart to separate files and pictures (with a larger storage need) from our main database. This helps reduce waiting when a user loads the entire data on a new device (and we could also avoid syncing files on a mobile device etc.)

Possible ways to do this:
* Use a second, separate PouchDB database for files
* Sync files to the server "directly" (i.e. not using PouchDB/CouchDB), that could also help with the upload bug #35

**Comment by sanindya-iiitd** [comment]
I'd suggest storing the heavy data some place else in an organized way.
And, in PouchDB only store information like the URL at which you can get this data. For example,
We can have a url that goes like: "http://db.cloud.com/children/<id>/"
Under this URL, we can have various data-files associated with the child whose child_id is <id>.

In the PouchDB that we sync, we only store textual information associated with the entities.

**Comment by sanindya-iiitd** [comment]
It'd be nice if there can be an option with the user if he/she really wants to sync the heavy database or not. At least, for the developers/testers, this option would be helpful.

**Comment by sebastian-leidig** [comment]
For now I'm going with a second pouchdb/couchdb database just for the files. This separation will be hidden in the `appDB` service - other code can just use `appDB.putFile()` and appDB.getFile()` without worrying where it will be stored.
