### ISSUE TITLE
Global Alert Service

### ISSUE THREAD

**Issue by fschoell** [NGO-DB/helgo_db#74]
We should have an alert service that can be used within the angularjs application and pushes notifications to the user.

**Comment by fschoell** [comment]
Something like this: https://jsfiddle.net/uberspeck/j46Yh/

**Comment by fschoell** [comment]
We can use angular-bootstrap which is already included: https://angular-ui.github.io/bootstrap/

**Comment by fschoell** [comment]
Closed in #78

**Comment by sebastian-leidig** [comment]
Great!

I was expecting the popups in the top right rather than left as some other applications show them there. And the navigation would be unobstructed by the alerts.

What do you think?

**Comment by ojauch** [comment]
Yes I think that would look better
